name: Documentation
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
  workflow_dispatch:
jobs:
  docs:
    name: Documentation
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate();
          '
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}